version: '2'
volumes:
  nextcloud:
  db:

services:
  db:
    image: mariadb:10.6
    restart: always
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=nextsqlroot
      - MYSQL_PASSWORD=nextsql
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  app:
    image: nextcloud:custom
    build: .  
    restart: always
    ports:
      - 8080:80
    links:
      - db
    volumes:
      - /home/nextcloud_docker:/var/www/html
      - /media/nextcloud_docker:/media/nextcloud_docker
    environment:
      - MYSQL_PASSWORD=nextsql
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db

